### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by lgoettgens** [JuliaTesting/Aqua.jl#310]
This issue contains a list of things that have to be done/changed in Aqua before I would call out a 1.0 release.
@ everyone feel free to comment your opinions to this below.

- [ ] docs: versioning strategy (x-ref https://github.com/JuliaTesting/Aqua.jl/issues/229)
- [ ] reduce code duplication in `test_all`; instead have some registering mechanism
- [ ] split different tests into submodules (x-ref https://github.com/JuliaTesting/Aqua.jl/pull/154)
- [ ] docs: how to add a new test
- go through the already existing tests, clean them up, resolve major issues:
  - [ ] `test_ambiguities`: 
    - [x] https://github.com/JuliaTesting/Aqua.jl/issues/77
    - [ ] https://github.com/JuliaTesting/Aqua.jl/issues/308
    - [ ] https://github.com/JuliaTesting/Aqua.jl/issues/290
    - [ ] make it somehow work with package extensions
    - [ ] re-work interface (more ways to interact than just the one `test_*` function)
  - [ ] `test_unbound_args`:
    - [ ] make it somehow work with package extensions
    - [ ] re-work interface (more ways to interact than just the one `test_*` function)
  - [ ] `test_undefined_exports`:
    - [ ] re-work interface (more ways to interact than just the one `test_*` function)
  - [ ] `test_stale_deps`:
    - [ ] https://github.com/JuliaTesting/Aqua.jl/issues/264
    - [ ] re-work interface (more ways to interact than just the one `test_*` function)
  - [ ] `test_project_extras`:
    - [ ] https://github.com/JuliaTesting/Aqua.jl/issues/251
    - [ ] Decide if this test is still needed.
  - [ ] `test_deps_compat`:
    - [ ] https://github.com/JuliaTesting/Aqua.jl/issues/294
  - [ ] `test_piracies`:
    - [ ] re-work interface (more ways to interact than just the one `test_*` function)
    - [ ] make it somehow work with package extensions
  - [ ] `test_persistent_tasks`:
    - [ ] https://github.com/JuliaTesting/Aqua.jl/issues/292

New tests: Since they have not been mentioned in the above list, I would like to add some things about them. Until the process to 1.0 is finished, I won't put any effort myself into adding new tests. If someone opens a PR with a new test, this will probably need to wait for some time where it can be incorporated in a between-version of this process, or even until 1.0 is finished, and then added as described in the versioning strategy.

**Comment by j-fu** [comment]
Why not release #313 as 1.0  and rename this issue to "2.0 Roadmap" ? This would give more maneuvering space between "new feature added" and "breaking" than for 0.x versions.

No code will be ever perfect, and IMHO Aqua is already good (and important) enough to have a 1.0 base version. 

I didn't have a look into the internals, though.
